# Generated by Django 4.2.3 on 2023-07-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=20)),
                ('publication_year', models.IntegerField()),
                ('publishing_company', models.CharField(max_length=15)),
            ],
        ),
    ]
